### ISSUE TITLE
ssu-rrna.org not found

### ISSUE THREAD

**Issue by sgmccalla** [frederic-mahe/stampa#2]
My browser cannot navigate to the http://ssu-rrna.org/ website.

**Comment by frederic-mahe** [comment]
Hi @SGMcCalla,

sadly the PR2 website disappeared a few month ago, and it should not come back anytime soon. There is a collective effort to rebuild a database of reference sequences for _Eukaryota_, but it is not usable yet. You can check it nonetheless, it is a cool project: http://unieuk.org/

**Comment by frederic-mahe** [comment]
A link to the new PR2 database is now included in the README
