### ISSUE TITLE
input file of stampa

### ISSUE THREAD

**Issue by weiichen** [frederic-mahe/stampa#3]
Hello Frederic,
I am trying to do "format the BoLD Cytochrome oxidase subunit 1 (COI) database" step with PR2 database.  

However, it showed like this...
/opt/sge/default/spool/n90/job_scripts/1270192: line 10: ${pr2_${VERSION}_taxo_long_Eukaryota.fasta}: bad substitution
which the log files showed cutadapt: error: File is neither FASTQ nor FASTA.

Do you know what might be the problem of this?
Thanks

Wei

**Comment by frederic-mahe** [comment]
Hi @weiichen , please send me a link to the COI database you want to use and I will show you how to prepare it for stampa.

**Comment by weiichen** [comment]
Hello @frederic-mahe 
actually I am trying the PR2 database for stampa but I got stuck for preparing the database.
Thanks.
Wei

**Comment by frederic-mahe** [comment]
Hi @weiichen, your bug does not seem to be related to stampa.

```sh
/opt/sge/default/spool/n90/job_scripts/1270192: line 10: ${pr2_${VERSION}_taxo_long_Eukaryota.fasta}: bad substitution
```

In your (bash?) script, you cannot nest substitution patterns `${ ${} }`.

**Comment by frederic-mahe** [comment]
The README now includes an example with the PR2 database.
